// Code generated by protoc-gen-go. DO NOT EDIT.
// source: manager.proto

// protoc --go_out=plugins=grpc:. *.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DashboardResponse_ValidatorStatus int32

const (
	DashboardResponse_Validating DashboardResponse_ValidatorStatus = 0
	DashboardResponse_Challenger DashboardResponse_ValidatorStatus = 1
	DashboardResponse_Offline    DashboardResponse_ValidatorStatus = 2
)

var DashboardResponse_ValidatorStatus_name = map[int32]string{
	0: "Validating",
	1: "Challenger",
	2: "Offline",
}

var DashboardResponse_ValidatorStatus_value = map[string]int32{
	"Validating": 0,
	"Challenger": 1,
	"Offline":    2,
}

func (x DashboardResponse_ValidatorStatus) String() string {
	return proto.EnumName(DashboardResponse_ValidatorStatus_name, int32(x))
}

func (DashboardResponse_ValidatorStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{5, 0}
}

type NodeInfo struct {
	ProtocolVersion      *NodeInfo_ProtocolVersion `protobuf:"bytes,8,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Id                   string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ListenAddr           string                    `protobuf:"bytes,2,opt,name=listen_addr,json=listenAddr,proto3" json:"listen_addr,omitempty"`
	Network              string                    `protobuf:"bytes,3,opt,name=network,proto3" json:"network,omitempty"`
	Version              string                    `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	Channels             string                    `protobuf:"bytes,5,opt,name=channels,proto3" json:"channels,omitempty"`
	Moniker              string                    `protobuf:"bytes,6,opt,name=moniker,proto3" json:"moniker,omitempty"`
	Other                *NodeInfo_Other           `protobuf:"bytes,7,opt,name=other,proto3" json:"other,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetProtocolVersion() *NodeInfo_ProtocolVersion {
	if m != nil {
		return m.ProtocolVersion
	}
	return nil
}

func (m *NodeInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeInfo) GetListenAddr() string {
	if m != nil {
		return m.ListenAddr
	}
	return ""
}

func (m *NodeInfo) GetNetwork() string {
	if m != nil {
		return m.Network
	}
	return ""
}

func (m *NodeInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *NodeInfo) GetChannels() string {
	if m != nil {
		return m.Channels
	}
	return ""
}

func (m *NodeInfo) GetMoniker() string {
	if m != nil {
		return m.Moniker
	}
	return ""
}

func (m *NodeInfo) GetOther() *NodeInfo_Other {
	if m != nil {
		return m.Other
	}
	return nil
}

type NodeInfo_ProtocolVersion struct {
	P2P                  uint64   `protobuf:"varint,3,opt,name=p2p,proto3" json:"p2p,omitempty"`
	Block                uint64   `protobuf:"varint,1,opt,name=block,proto3" json:"block,omitempty"`
	App                  uint64   `protobuf:"varint,2,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo_ProtocolVersion) Reset()         { *m = NodeInfo_ProtocolVersion{} }
func (m *NodeInfo_ProtocolVersion) String() string { return proto.CompactTextString(m) }
func (*NodeInfo_ProtocolVersion) ProtoMessage()    {}
func (*NodeInfo_ProtocolVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0, 0}
}

func (m *NodeInfo_ProtocolVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Unmarshal(m, b)
}
func (m *NodeInfo_ProtocolVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Marshal(b, m, deterministic)
}
func (m *NodeInfo_ProtocolVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo_ProtocolVersion.Merge(m, src)
}
func (m *NodeInfo_ProtocolVersion) XXX_Size() int {
	return xxx_messageInfo_NodeInfo_ProtocolVersion.Size(m)
}
func (m *NodeInfo_ProtocolVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo_ProtocolVersion.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo_ProtocolVersion proto.InternalMessageInfo

func (m *NodeInfo_ProtocolVersion) GetP2P() uint64 {
	if m != nil {
		return m.P2P
	}
	return 0
}

func (m *NodeInfo_ProtocolVersion) GetBlock() uint64 {
	if m != nil {
		return m.Block
	}
	return 0
}

func (m *NodeInfo_ProtocolVersion) GetApp() uint64 {
	if m != nil {
		return m.App
	}
	return 0
}

type NodeInfo_Other struct {
	TxIndex              string   `protobuf:"bytes,2,opt,name=tx_index,json=txIndex,proto3" json:"tx_index,omitempty"`
	RpcAddress           string   `protobuf:"bytes,1,opt,name=rpc_address,json=rpcAddress,proto3" json:"rpc_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo_Other) Reset()         { *m = NodeInfo_Other{} }
func (m *NodeInfo_Other) String() string { return proto.CompactTextString(m) }
func (*NodeInfo_Other) ProtoMessage()    {}
func (*NodeInfo_Other) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{0, 1}
}

func (m *NodeInfo_Other) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo_Other.Unmarshal(m, b)
}
func (m *NodeInfo_Other) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo_Other.Marshal(b, m, deterministic)
}
func (m *NodeInfo_Other) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo_Other.Merge(m, src)
}
func (m *NodeInfo_Other) XXX_Size() int {
	return xxx_messageInfo_NodeInfo_Other.Size(m)
}
func (m *NodeInfo_Other) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo_Other.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo_Other proto.InternalMessageInfo

func (m *NodeInfo_Other) GetTxIndex() string {
	if m != nil {
		return m.TxIndex
	}
	return ""
}

func (m *NodeInfo_Other) GetRpcAddress() string {
	if m != nil {
		return m.RpcAddress
	}
	return ""
}

type NetInfoResponse struct {
	Listening            bool                    `protobuf:"varint,4,opt,name=listening,proto3" json:"listening,omitempty"`
	Listeners            []string                `protobuf:"bytes,1,rep,name=listeners,proto3" json:"listeners,omitempty"`
	NPeers               int64                   `protobuf:"varint,2,opt,name=n_peers,json=nPeers,proto3" json:"n_peers,omitempty"`
	Peers                []*NetInfoResponse_Peer `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NetInfoResponse) Reset()         { *m = NetInfoResponse{} }
func (m *NetInfoResponse) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse) ProtoMessage()    {}
func (*NetInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1}
}

func (m *NetInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse.Unmarshal(m, b)
}
func (m *NetInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse.Merge(m, src)
}
func (m *NetInfoResponse) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse.Size(m)
}
func (m *NetInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse proto.InternalMessageInfo

func (m *NetInfoResponse) GetListening() bool {
	if m != nil {
		return m.Listening
	}
	return false
}

func (m *NetInfoResponse) GetListeners() []string {
	if m != nil {
		return m.Listeners
	}
	return nil
}

func (m *NetInfoResponse) GetNPeers() int64 {
	if m != nil {
		return m.NPeers
	}
	return 0
}

func (m *NetInfoResponse) GetPeers() []*NetInfoResponse_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type NetInfoResponse_Peer struct {
	NodeInfo             *NodeInfo                              `protobuf:"bytes,4,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	IsOutbound           bool                                   `protobuf:"varint,1,opt,name=is_outbound,json=isOutbound,proto3" json:"is_outbound,omitempty"`
	ConnectionStatus     *NetInfoResponse_Peer_ConnectionStatus `protobuf:"bytes,2,opt,name=connection_status,json=connectionStatus,proto3" json:"connection_status,omitempty"`
	RemoteIp             string                                 `protobuf:"bytes,3,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *NetInfoResponse_Peer) Reset()         { *m = NetInfoResponse_Peer{} }
func (m *NetInfoResponse_Peer) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse_Peer) ProtoMessage()    {}
func (*NetInfoResponse_Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1, 0}
}

func (m *NetInfoResponse_Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Peer.Unmarshal(m, b)
}
func (m *NetInfoResponse_Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Peer.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Peer.Merge(m, src)
}
func (m *NetInfoResponse_Peer) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Peer.Size(m)
}
func (m *NetInfoResponse_Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Peer proto.InternalMessageInfo

func (m *NetInfoResponse_Peer) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *NetInfoResponse_Peer) GetIsOutbound() bool {
	if m != nil {
		return m.IsOutbound
	}
	return false
}

func (m *NetInfoResponse_Peer) GetConnectionStatus() *NetInfoResponse_Peer_ConnectionStatus {
	if m != nil {
		return m.ConnectionStatus
	}
	return nil
}

func (m *NetInfoResponse_Peer) GetRemoteIp() string {
	if m != nil {
		return m.RemoteIp
	}
	return ""
}

type NetInfoResponse_Peer_ConnectionStatus struct {
	Duration             int64                                            `protobuf:"varint,4,opt,name=Duration,proto3" json:"Duration,omitempty"`
	SendMonitor          *NetInfoResponse_Peer_ConnectionStatus_Monitor   `protobuf:"bytes,1,opt,name=SendMonitor,proto3" json:"SendMonitor,omitempty"`
	RecvMonitor          *NetInfoResponse_Peer_ConnectionStatus_Monitor   `protobuf:"bytes,2,opt,name=RecvMonitor,proto3" json:"RecvMonitor,omitempty"`
	Channels             []*NetInfoResponse_Peer_ConnectionStatus_Channel `protobuf:"bytes,3,rep,name=Channels,proto3" json:"Channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *NetInfoResponse_Peer_ConnectionStatus) Reset()         { *m = NetInfoResponse_Peer_ConnectionStatus{} }
func (m *NetInfoResponse_Peer_ConnectionStatus) String() string { return proto.CompactTextString(m) }
func (*NetInfoResponse_Peer_ConnectionStatus) ProtoMessage()    {}
func (*NetInfoResponse_Peer_ConnectionStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1, 0, 0}
}

func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.Unmarshal(m, b)
}
func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.Merge(m, src)
}
func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.Size(m)
}
func (m *NetInfoResponse_Peer_ConnectionStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus proto.InternalMessageInfo

func (m *NetInfoResponse_Peer_ConnectionStatus) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus) GetSendMonitor() *NetInfoResponse_Peer_ConnectionStatus_Monitor {
	if m != nil {
		return m.SendMonitor
	}
	return nil
}

func (m *NetInfoResponse_Peer_ConnectionStatus) GetRecvMonitor() *NetInfoResponse_Peer_ConnectionStatus_Monitor {
	if m != nil {
		return m.RecvMonitor
	}
	return nil
}

func (m *NetInfoResponse_Peer_ConnectionStatus) GetChannels() []*NetInfoResponse_Peer_ConnectionStatus_Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type NetInfoResponse_Peer_ConnectionStatus_Monitor struct {
	Active               bool     `protobuf:"varint,13,opt,name=Active,proto3" json:"Active,omitempty"`
	Start                string   `protobuf:"bytes,1,opt,name=Start,proto3" json:"Start,omitempty"`
	Duration             int64    `protobuf:"varint,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Idle                 int64    `protobuf:"varint,3,opt,name=Idle,proto3" json:"Idle,omitempty"`
	Bytes                int64    `protobuf:"varint,4,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Samples              int64    `protobuf:"varint,5,opt,name=Samples,proto3" json:"Samples,omitempty"`
	InstRate             int64    `protobuf:"varint,6,opt,name=InstRate,proto3" json:"InstRate,omitempty"`
	CurRate              int64    `protobuf:"varint,7,opt,name=CurRate,proto3" json:"CurRate,omitempty"`
	AvgRate              int64    `protobuf:"varint,8,opt,name=AvgRate,proto3" json:"AvgRate,omitempty"`
	PeakRate             int64    `protobuf:"varint,9,opt,name=PeakRate,proto3" json:"PeakRate,omitempty"`
	BytesRem             int64    `protobuf:"varint,10,opt,name=BytesRem,proto3" json:"BytesRem,omitempty"`
	TimeRem              int64    `protobuf:"varint,11,opt,name=TimeRem,proto3" json:"TimeRem,omitempty"`
	Progress             uint32   `protobuf:"varint,12,opt,name=Progress,proto3" json:"Progress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) Reset() {
	*m = NetInfoResponse_Peer_ConnectionStatus_Monitor{}
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) String() string {
	return proto.CompactTextString(m)
}
func (*NetInfoResponse_Peer_ConnectionStatus_Monitor) ProtoMessage() {}
func (*NetInfoResponse_Peer_ConnectionStatus_Monitor) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1, 0, 0, 0}
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.Unmarshal(m, b)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.Merge(m, src)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.Size(m)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Monitor proto.InternalMessageInfo

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetIdle() int64 {
	if m != nil {
		return m.Idle
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetBytes() int64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetSamples() int64 {
	if m != nil {
		return m.Samples
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetInstRate() int64 {
	if m != nil {
		return m.InstRate
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetCurRate() int64 {
	if m != nil {
		return m.CurRate
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetAvgRate() int64 {
	if m != nil {
		return m.AvgRate
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetPeakRate() int64 {
	if m != nil {
		return m.PeakRate
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetBytesRem() int64 {
	if m != nil {
		return m.BytesRem
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetTimeRem() int64 {
	if m != nil {
		return m.TimeRem
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Monitor) GetProgress() uint32 {
	if m != nil {
		return m.Progress
	}
	return 0
}

type NetInfoResponse_Peer_ConnectionStatus_Channel struct {
	ID                   int32    `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
	SendQueueCapacity    int64    `protobuf:"varint,1,opt,name=SendQueueCapacity,proto3" json:"SendQueueCapacity,omitempty"`
	SendQueueSize        int64    `protobuf:"varint,2,opt,name=SendQueueSize,proto3" json:"SendQueueSize,omitempty"`
	Priority             int64    `protobuf:"varint,3,opt,name=Priority,proto3" json:"Priority,omitempty"`
	RecentlySent         int64    `protobuf:"varint,4,opt,name=RecentlySent,proto3" json:"RecentlySent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) Reset() {
	*m = NetInfoResponse_Peer_ConnectionStatus_Channel{}
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) String() string {
	return proto.CompactTextString(m)
}
func (*NetInfoResponse_Peer_ConnectionStatus_Channel) ProtoMessage() {}
func (*NetInfoResponse_Peer_ConnectionStatus_Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{1, 0, 0, 1}
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.Unmarshal(m, b)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.Marshal(b, m, deterministic)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.Merge(m, src)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_Size() int {
	return xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.Size(m)
}
func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_NetInfoResponse_Peer_ConnectionStatus_Channel proto.InternalMessageInfo

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetSendQueueCapacity() int64 {
	if m != nil {
		return m.SendQueueCapacity
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetSendQueueSize() int64 {
	if m != nil {
		return m.SendQueueSize
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *NetInfoResponse_Peer_ConnectionStatus_Channel) GetRecentlySent() int64 {
	if m != nil {
		return m.RecentlySent
	}
	return 0
}

type StatusResponse struct {
	Version              string                   `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	LatestBlockHash      string                   `protobuf:"bytes,1,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	LatestAppHash        string                   `protobuf:"bytes,2,opt,name=latest_app_hash,json=latestAppHash,proto3" json:"latest_app_hash,omitempty"`
	LatestBlockHeight    int64                    `protobuf:"varint,3,opt,name=latest_block_height,json=latestBlockHeight,proto3" json:"latest_block_height,omitempty"`
	LatestBlockTime      string                   `protobuf:"bytes,4,opt,name=latest_block_time,json=latestBlockTime,proto3" json:"latest_block_time,omitempty"`
	KeepLastStates       int64                    `protobuf:"varint,5,opt,name=keep_last_states,json=keepLastStates,proto3" json:"keep_last_states,omitempty"`
	TmStatus             *StatusResponse_TmStatus `protobuf:"bytes,6,opt,name=tm_status,json=tmStatus,proto3" json:"tm_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *StatusResponse) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

func (m *StatusResponse) GetLatestAppHash() string {
	if m != nil {
		return m.LatestAppHash
	}
	return ""
}

func (m *StatusResponse) GetLatestBlockHeight() int64 {
	if m != nil {
		return m.LatestBlockHeight
	}
	return 0
}

func (m *StatusResponse) GetLatestBlockTime() string {
	if m != nil {
		return m.LatestBlockTime
	}
	return ""
}

func (m *StatusResponse) GetKeepLastStates() int64 {
	if m != nil {
		return m.KeepLastStates
	}
	return 0
}

func (m *StatusResponse) GetTmStatus() *StatusResponse_TmStatus {
	if m != nil {
		return m.TmStatus
	}
	return nil
}

type StatusResponse_TmStatus struct {
	NodeInfo             *NodeInfo                              `protobuf:"bytes,3,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	SyncInfo             *StatusResponse_TmStatus_SyncInfo      `protobuf:"bytes,1,opt,name=sync_info,json=syncInfo,proto3" json:"sync_info,omitempty"`
	ValidatorInfo        *StatusResponse_TmStatus_ValidatorInfo `protobuf:"bytes,2,opt,name=validator_info,json=validatorInfo,proto3" json:"validator_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *StatusResponse_TmStatus) Reset()         { *m = StatusResponse_TmStatus{} }
func (m *StatusResponse_TmStatus) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_TmStatus) ProtoMessage()    {}
func (*StatusResponse_TmStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2, 0}
}

func (m *StatusResponse_TmStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_TmStatus.Unmarshal(m, b)
}
func (m *StatusResponse_TmStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_TmStatus.Marshal(b, m, deterministic)
}
func (m *StatusResponse_TmStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_TmStatus.Merge(m, src)
}
func (m *StatusResponse_TmStatus) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_TmStatus.Size(m)
}
func (m *StatusResponse_TmStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_TmStatus.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_TmStatus proto.InternalMessageInfo

func (m *StatusResponse_TmStatus) GetNodeInfo() *NodeInfo {
	if m != nil {
		return m.NodeInfo
	}
	return nil
}

func (m *StatusResponse_TmStatus) GetSyncInfo() *StatusResponse_TmStatus_SyncInfo {
	if m != nil {
		return m.SyncInfo
	}
	return nil
}

func (m *StatusResponse_TmStatus) GetValidatorInfo() *StatusResponse_TmStatus_ValidatorInfo {
	if m != nil {
		return m.ValidatorInfo
	}
	return nil
}

type StatusResponse_TmStatus_SyncInfo struct {
	LatestBlockHash      string   `protobuf:"bytes,5,opt,name=latest_block_hash,json=latestBlockHash,proto3" json:"latest_block_hash,omitempty"`
	LatestAppHash        string   `protobuf:"bytes,1,opt,name=latest_app_hash,json=latestAppHash,proto3" json:"latest_app_hash,omitempty"`
	LatestBlockHeight    int64    `protobuf:"varint,2,opt,name=latest_block_height,json=latestBlockHeight,proto3" json:"latest_block_height,omitempty"`
	LatestBlockTime      string   `protobuf:"bytes,3,opt,name=latest_block_time,json=latestBlockTime,proto3" json:"latest_block_time,omitempty"`
	CatchingUp           bool     `protobuf:"varint,4,opt,name=catching_up,json=catchingUp,proto3" json:"catching_up,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse_TmStatus_SyncInfo) Reset()         { *m = StatusResponse_TmStatus_SyncInfo{} }
func (m *StatusResponse_TmStatus_SyncInfo) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_TmStatus_SyncInfo) ProtoMessage()    {}
func (*StatusResponse_TmStatus_SyncInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2, 0, 0}
}

func (m *StatusResponse_TmStatus_SyncInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.Unmarshal(m, b)
}
func (m *StatusResponse_TmStatus_SyncInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.Marshal(b, m, deterministic)
}
func (m *StatusResponse_TmStatus_SyncInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.Merge(m, src)
}
func (m *StatusResponse_TmStatus_SyncInfo) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.Size(m)
}
func (m *StatusResponse_TmStatus_SyncInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_TmStatus_SyncInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_TmStatus_SyncInfo proto.InternalMessageInfo

func (m *StatusResponse_TmStatus_SyncInfo) GetLatestBlockHash() string {
	if m != nil {
		return m.LatestBlockHash
	}
	return ""
}

func (m *StatusResponse_TmStatus_SyncInfo) GetLatestAppHash() string {
	if m != nil {
		return m.LatestAppHash
	}
	return ""
}

func (m *StatusResponse_TmStatus_SyncInfo) GetLatestBlockHeight() int64 {
	if m != nil {
		return m.LatestBlockHeight
	}
	return 0
}

func (m *StatusResponse_TmStatus_SyncInfo) GetLatestBlockTime() string {
	if m != nil {
		return m.LatestBlockTime
	}
	return ""
}

func (m *StatusResponse_TmStatus_SyncInfo) GetCatchingUp() bool {
	if m != nil {
		return m.CatchingUp
	}
	return false
}

type StatusResponse_TmStatus_ValidatorInfo struct {
	Address              string                                        `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	PubKey               *StatusResponse_TmStatus_ValidatorInfo_PubKey `protobuf:"bytes,1,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	VotingPower          int64                                         `protobuf:"varint,2,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *StatusResponse_TmStatus_ValidatorInfo) Reset()         { *m = StatusResponse_TmStatus_ValidatorInfo{} }
func (m *StatusResponse_TmStatus_ValidatorInfo) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_TmStatus_ValidatorInfo) ProtoMessage()    {}
func (*StatusResponse_TmStatus_ValidatorInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2, 0, 1}
}

func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.Unmarshal(m, b)
}
func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.Marshal(b, m, deterministic)
}
func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.Merge(m, src)
}
func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.Size(m)
}
func (m *StatusResponse_TmStatus_ValidatorInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo proto.InternalMessageInfo

func (m *StatusResponse_TmStatus_ValidatorInfo) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StatusResponse_TmStatus_ValidatorInfo) GetPubKey() *StatusResponse_TmStatus_ValidatorInfo_PubKey {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *StatusResponse_TmStatus_ValidatorInfo) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

type StatusResponse_TmStatus_ValidatorInfo_PubKey struct {
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) Reset() {
	*m = StatusResponse_TmStatus_ValidatorInfo_PubKey{}
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) String() string {
	return proto.CompactTextString(m)
}
func (*StatusResponse_TmStatus_ValidatorInfo_PubKey) ProtoMessage() {}
func (*StatusResponse_TmStatus_ValidatorInfo_PubKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{2, 0, 1, 0}
}

func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.Unmarshal(m, b)
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.Marshal(b, m, deterministic)
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.Merge(m, src)
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.Size(m)
}
func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_TmStatus_ValidatorInfo_PubKey proto.InternalMessageInfo

func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StatusResponse_TmStatus_ValidatorInfo_PubKey) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type PruneBlocksRequest struct {
	FromHeight           int64    `protobuf:"varint,1,opt,name=from_height,json=fromHeight,proto3" json:"from_height,omitempty"`
	ToHeight             int64    `protobuf:"varint,2,opt,name=to_height,json=toHeight,proto3" json:"to_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PruneBlocksRequest) Reset()         { *m = PruneBlocksRequest{} }
func (m *PruneBlocksRequest) String() string { return proto.CompactTextString(m) }
func (*PruneBlocksRequest) ProtoMessage()    {}
func (*PruneBlocksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{3}
}

func (m *PruneBlocksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PruneBlocksRequest.Unmarshal(m, b)
}
func (m *PruneBlocksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PruneBlocksRequest.Marshal(b, m, deterministic)
}
func (m *PruneBlocksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PruneBlocksRequest.Merge(m, src)
}
func (m *PruneBlocksRequest) XXX_Size() int {
	return xxx_messageInfo_PruneBlocksRequest.Size(m)
}
func (m *PruneBlocksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PruneBlocksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PruneBlocksRequest proto.InternalMessageInfo

func (m *PruneBlocksRequest) GetFromHeight() int64 {
	if m != nil {
		return m.FromHeight
	}
	return 0
}

func (m *PruneBlocksRequest) GetToHeight() int64 {
	if m != nil {
		return m.ToHeight
	}
	return 0
}

type DealPeerRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Persistent           bool     `protobuf:"varint,2,opt,name=persistent,proto3" json:"persistent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DealPeerRequest) Reset()         { *m = DealPeerRequest{} }
func (m *DealPeerRequest) String() string { return proto.CompactTextString(m) }
func (*DealPeerRequest) ProtoMessage()    {}
func (*DealPeerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{4}
}

func (m *DealPeerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DealPeerRequest.Unmarshal(m, b)
}
func (m *DealPeerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DealPeerRequest.Marshal(b, m, deterministic)
}
func (m *DealPeerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DealPeerRequest.Merge(m, src)
}
func (m *DealPeerRequest) XXX_Size() int {
	return xxx_messageInfo_DealPeerRequest.Size(m)
}
func (m *DealPeerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DealPeerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DealPeerRequest proto.InternalMessageInfo

func (m *DealPeerRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *DealPeerRequest) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

type DashboardResponse struct {
	LatestHeight           int64                             `protobuf:"varint,1,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	Timestamp              *timestamp.Timestamp              `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Duration               int64                             `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	MemoryUsage            uint64                            `protobuf:"varint,4,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	ValidatorPubKey        string                            `protobuf:"bytes,5,opt,name=validator_pub_key,json=validatorPubKey,proto3" json:"validator_pub_key,omitempty"`
	MaxPeerHeight          int64                             `protobuf:"varint,6,opt,name=max_peer_height,json=maxPeerHeight,proto3" json:"max_peer_height,omitempty"`
	PeersCount             int32                             `protobuf:"varint,7,opt,name=peers_count,json=peersCount,proto3" json:"peers_count,omitempty"`
	AvgBlockProcessingTime int64                             `protobuf:"varint,8,opt,name=avg_block_processing_time,json=avgBlockProcessingTime,proto3" json:"avg_block_processing_time,omitempty"`
	TimePerBlock           int64                             `protobuf:"varint,9,opt,name=time_per_block,json=timePerBlock,proto3" json:"time_per_block,omitempty"`
	MissedBlocks           string                            `protobuf:"bytes,10,opt,name=missed_blocks,json=missedBlocks,proto3" json:"missed_blocks,omitempty"`
	VotingPower            int64                             `protobuf:"varint,11,opt,name=voting_power,json=votingPower,proto3" json:"voting_power,omitempty"`
	Stake                  string                            `protobuf:"bytes,12,opt,name=stake,proto3" json:"stake,omitempty"`
	ValidatorStatus        DashboardResponse_ValidatorStatus `protobuf:"varint,13,opt,name=validator_status,json=validatorStatus,proto3,enum=pb.DashboardResponse_ValidatorStatus" json:"validator_status,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                          `json:"-"`
	XXX_unrecognized       []byte                            `json:"-"`
	XXX_sizecache          int32                             `json:"-"`
}

func (m *DashboardResponse) Reset()         { *m = DashboardResponse{} }
func (m *DashboardResponse) String() string { return proto.CompactTextString(m) }
func (*DashboardResponse) ProtoMessage()    {}
func (*DashboardResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cde9ec64f0d2c859, []int{5}
}

func (m *DashboardResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DashboardResponse.Unmarshal(m, b)
}
func (m *DashboardResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DashboardResponse.Marshal(b, m, deterministic)
}
func (m *DashboardResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DashboardResponse.Merge(m, src)
}
func (m *DashboardResponse) XXX_Size() int {
	return xxx_messageInfo_DashboardResponse.Size(m)
}
func (m *DashboardResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DashboardResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DashboardResponse proto.InternalMessageInfo

func (m *DashboardResponse) GetLatestHeight() int64 {
	if m != nil {
		return m.LatestHeight
	}
	return 0
}

func (m *DashboardResponse) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *DashboardResponse) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *DashboardResponse) GetMemoryUsage() uint64 {
	if m != nil {
		return m.MemoryUsage
	}
	return 0
}

func (m *DashboardResponse) GetValidatorPubKey() string {
	if m != nil {
		return m.ValidatorPubKey
	}
	return ""
}

func (m *DashboardResponse) GetMaxPeerHeight() int64 {
	if m != nil {
		return m.MaxPeerHeight
	}
	return 0
}

func (m *DashboardResponse) GetPeersCount() int32 {
	if m != nil {
		return m.PeersCount
	}
	return 0
}

func (m *DashboardResponse) GetAvgBlockProcessingTime() int64 {
	if m != nil {
		return m.AvgBlockProcessingTime
	}
	return 0
}

func (m *DashboardResponse) GetTimePerBlock() int64 {
	if m != nil {
		return m.TimePerBlock
	}
	return 0
}

func (m *DashboardResponse) GetMissedBlocks() string {
	if m != nil {
		return m.MissedBlocks
	}
	return ""
}

func (m *DashboardResponse) GetVotingPower() int64 {
	if m != nil {
		return m.VotingPower
	}
	return 0
}

func (m *DashboardResponse) GetStake() string {
	if m != nil {
		return m.Stake
	}
	return ""
}

func (m *DashboardResponse) GetValidatorStatus() DashboardResponse_ValidatorStatus {
	if m != nil {
		return m.ValidatorStatus
	}
	return DashboardResponse_Validating
}

func init() {
	proto.RegisterEnum("pb.DashboardResponse_ValidatorStatus", DashboardResponse_ValidatorStatus_name, DashboardResponse_ValidatorStatus_value)
	proto.RegisterType((*NodeInfo)(nil), "pb.NodeInfo")
	proto.RegisterType((*NodeInfo_ProtocolVersion)(nil), "pb.NodeInfo.ProtocolVersion")
	proto.RegisterType((*NodeInfo_Other)(nil), "pb.NodeInfo.Other")
	proto.RegisterType((*NetInfoResponse)(nil), "pb.NetInfoResponse")
	proto.RegisterType((*NetInfoResponse_Peer)(nil), "pb.NetInfoResponse.Peer")
	proto.RegisterType((*NetInfoResponse_Peer_ConnectionStatus)(nil), "pb.NetInfoResponse.Peer.ConnectionStatus")
	proto.RegisterType((*NetInfoResponse_Peer_ConnectionStatus_Monitor)(nil), "pb.NetInfoResponse.Peer.ConnectionStatus.Monitor")
	proto.RegisterType((*NetInfoResponse_Peer_ConnectionStatus_Channel)(nil), "pb.NetInfoResponse.Peer.ConnectionStatus.Channel")
	proto.RegisterType((*StatusResponse)(nil), "pb.StatusResponse")
	proto.RegisterType((*StatusResponse_TmStatus)(nil), "pb.StatusResponse.TmStatus")
	proto.RegisterType((*StatusResponse_TmStatus_SyncInfo)(nil), "pb.StatusResponse.TmStatus.SyncInfo")
	proto.RegisterType((*StatusResponse_TmStatus_ValidatorInfo)(nil), "pb.StatusResponse.TmStatus.ValidatorInfo")
	proto.RegisterType((*StatusResponse_TmStatus_ValidatorInfo_PubKey)(nil), "pb.StatusResponse.TmStatus.ValidatorInfo.PubKey")
	proto.RegisterType((*PruneBlocksRequest)(nil), "pb.PruneBlocksRequest")
	proto.RegisterType((*DealPeerRequest)(nil), "pb.DealPeerRequest")
	proto.RegisterType((*DashboardResponse)(nil), "pb.DashboardResponse")
}

func init() { proto.RegisterFile("manager.proto", fileDescriptor_cde9ec64f0d2c859) }

var fileDescriptor_cde9ec64f0d2c859 = []byte{
	// 1528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0x23, 0x49,
	0x15, 0xc6, 0xff, 0xed, 0xd3, 0xb1, 0xe3, 0xd4, 0x42, 0xf0, 0x76, 0x56, 0x24, 0x98, 0x61, 0x95,
	0x45, 0xc8, 0xbb, 0x18, 0xc4, 0x8f, 0x04, 0x48, 0xd9, 0x04, 0x81, 0x35, 0xcc, 0x8e, 0x29, 0xcf,
	0xcc, 0x6d, 0xab, 0xdc, 0x3e, 0xb1, 0x5b, 0xe9, 0xae, 0x2a, 0xba, 0xab, 0x3d, 0x31, 0x8f, 0xc1,
	0x63, 0x20, 0x21, 0x6e, 0x90, 0x78, 0x08, 0xae, 0xb9, 0xe2, 0x3d, 0x40, 0xdc, 0xa1, 0xfa, 0x69,
	0xff, 0xc4, 0xc9, 0x68, 0x66, 0xaf, 0xd2, 0xe7, 0x3b, 0xa7, 0x3e, 0x9f, 0xfa, 0xea, 0x9c, 0x53,
	0x15, 0xe8, 0xa4, 0x8c, 0xb3, 0x05, 0x66, 0x43, 0x99, 0x09, 0x25, 0x48, 0x55, 0xce, 0x82, 0xb3,
	0x85, 0x10, 0x8b, 0x04, 0x3f, 0x37, 0xc8, 0xac, 0xb8, 0xfd, 0x1c, 0x53, 0xa9, 0xd6, 0x36, 0x20,
	0x38, 0x7f, 0xe8, 0x54, 0x71, 0x8a, 0xb9, 0x62, 0xa9, 0xb4, 0x01, 0x83, 0xbf, 0xd4, 0xc0, 0xfb,
	0x4a, 0xcc, 0x71, 0xcc, 0x6f, 0x05, 0xf9, 0x2d, 0xf4, 0x0c, 0x1a, 0x89, 0x24, 0x5c, 0x61, 0x96,
	0xc7, 0x82, 0xf7, 0xbd, 0x8b, 0xca, 0xa5, 0x3f, 0xfa, 0x64, 0x28, 0x67, 0xc3, 0x32, 0x6e, 0x38,
	0x71, 0x41, 0x6f, 0x6c, 0x0c, 0x3d, 0x96, 0xfb, 0x00, 0xe9, 0x42, 0x35, 0x9e, 0xf7, 0x2b, 0x17,
	0x95, 0xcb, 0x36, 0xad, 0xc6, 0x73, 0x72, 0x0e, 0x7e, 0x12, 0xe7, 0x0a, 0x79, 0xc8, 0xe6, 0xf3,
	0xac, 0x5f, 0x35, 0x0e, 0xb0, 0xd0, 0xd5, 0x7c, 0x9e, 0x91, 0x3e, 0xb4, 0x38, 0xaa, 0xb7, 0x22,
	0xbb, 0xeb, 0xd7, 0x8c, 0xb3, 0x34, 0xb5, 0xa7, 0x4c, 0xa5, 0x6e, 0x3d, 0xce, 0x24, 0x01, 0x78,
	0xd1, 0x92, 0x71, 0x8e, 0x49, 0xde, 0x6f, 0x18, 0xd7, 0xc6, 0xd6, 0xab, 0x52, 0xc1, 0xe3, 0x3b,
	0xcc, 0xfa, 0x4d, 0xbb, 0xca, 0x99, 0xe4, 0x12, 0x1a, 0x42, 0x2d, 0x31, 0xeb, 0xb7, 0xcc, 0xc6,
	0xc8, 0xde, 0xc6, 0x5e, 0x6a, 0x0f, 0xb5, 0x01, 0xc1, 0x73, 0x38, 0x7e, 0xb0, 0x51, 0xd2, 0x83,
	0x9a, 0x1c, 0x49, 0x93, 0x62, 0x9d, 0xea, 0x4f, 0xf2, 0x4d, 0x68, 0xcc, 0x12, 0x11, 0xdd, 0x99,
	0xcd, 0xd6, 0xa9, 0x35, 0x74, 0x1c, 0x93, 0xd2, 0xec, 0xb3, 0x4e, 0xf5, 0x67, 0x70, 0x0d, 0x0d,
	0x43, 0x4e, 0x3e, 0x06, 0x4f, 0xdd, 0x87, 0x31, 0x9f, 0xe3, 0xbd, 0xd3, 0xa1, 0xa5, 0xee, 0xc7,
	0xda, 0xd4, 0x2a, 0x65, 0x32, 0x32, 0x12, 0x61, 0x9e, 0x3b, 0xf9, 0x20, 0x93, 0xd1, 0x95, 0x45,
	0x06, 0x7f, 0x6e, 0xc3, 0xf1, 0x57, 0xa8, 0x74, 0xaa, 0x14, 0x73, 0x29, 0x78, 0x8e, 0xe4, 0x13,
	0x68, 0x5b, 0x1d, 0x63, 0xbe, 0x30, 0x0a, 0x79, 0x74, 0x0b, 0x6c, 0xbd, 0x98, 0x69, 0xc2, 0xda,
	0x65, 0x9b, 0x6e, 0x01, 0xf2, 0x6d, 0x68, 0xf1, 0x50, 0xa2, 0xf6, 0xe9, 0x54, 0x6a, 0xb4, 0xc9,
	0x27, 0xda, 0x22, 0x43, 0x68, 0x58, 0xb8, 0x76, 0x51, 0xbb, 0xf4, 0x47, 0x7d, 0x23, 0xd2, 0xfe,
	0x0f, 0x0f, 0x75, 0x24, 0xb5, 0x61, 0xc1, 0xff, 0x5a, 0x50, 0xd7, 0x36, 0xf9, 0x0c, 0xda, 0x5c,
	0xcc, 0x31, 0x8c, 0xf9, 0xad, 0x30, 0xd9, 0xf8, 0xa3, 0xa3, 0x5d, 0x85, 0xa9, 0xc7, 0xcb, 0x62,
	0x3b, 0x07, 0x3f, 0xce, 0x43, 0x51, 0xa8, 0x99, 0x28, 0xb8, 0x2d, 0x16, 0x8f, 0x42, 0x9c, 0xbf,
	0x74, 0x08, 0x79, 0x03, 0x27, 0x91, 0xe0, 0x1c, 0x23, 0x15, 0x0b, 0x1e, 0xe6, 0x8a, 0xa9, 0xc2,
	0xe6, 0xe9, 0x8f, 0x3e, 0x7b, 0x2a, 0xa1, 0xe1, 0xf5, 0x66, 0xc5, 0xd4, 0x2c, 0xa0, 0xbd, 0xe8,
	0x01, 0x42, 0xce, 0xa0, 0x9d, 0x61, 0x2a, 0x14, 0x86, 0xb1, 0x74, 0xd5, 0xe6, 0x59, 0x60, 0x2c,
	0x83, 0xbf, 0x35, 0xa1, 0xf7, 0x90, 0x43, 0x57, 0xda, 0x4d, 0x91, 0x31, 0x55, 0x16, 0x61, 0x8d,
	0x6e, 0x6c, 0x32, 0x05, 0x7f, 0x8a, 0x7c, 0xfe, 0x42, 0xf0, 0x58, 0x89, 0xcc, 0x6c, 0xc3, 0x1f,
	0xfd, 0xe8, 0xbd, 0xf3, 0x1b, 0xba, 0x85, 0x74, 0x97, 0x45, 0x93, 0x52, 0x8c, 0x56, 0x25, 0x69,
	0xf5, 0x6b, 0x93, 0xee, 0xb0, 0x90, 0x17, 0xe0, 0x5d, 0x97, 0xfd, 0x62, 0xcf, 0xf5, 0x03, 0x18,
	0xdd, 0x4a, 0xba, 0xa1, 0x08, 0xfe, 0x55, 0x85, 0x56, 0x49, 0x7d, 0x0a, 0xcd, 0xab, 0x48, 0xc5,
	0x2b, 0xec, 0x77, 0xcc, 0x31, 0x3a, 0x4b, 0x77, 0xc7, 0x54, 0xb1, 0x4c, 0xb9, 0x5a, 0xb6, 0xc6,
	0x9e, 0x9c, 0xd5, 0x07, 0x72, 0x12, 0xa8, 0x8f, 0xe7, 0x09, 0x9a, 0x73, 0xa9, 0x51, 0xf3, 0xad,
	0x59, 0xbe, 0x5c, 0x2b, 0xcc, 0x9d, 0xf6, 0xd6, 0xd0, 0x2d, 0x3e, 0x65, 0xa9, 0x4c, 0xd0, 0x76,
	0x7f, 0x8d, 0x96, 0xa6, 0xe6, 0x1f, 0xf3, 0x5c, 0x51, 0xa6, 0xd0, 0x74, 0x7f, 0x8d, 0x6e, 0x6c,
	0xbd, 0xea, 0xba, 0xc8, 0x8c, 0xab, 0x65, 0x57, 0x39, 0x53, 0x7b, 0xae, 0x56, 0x0b, 0xe3, 0xf1,
	0xac, 0xc7, 0x99, 0x9a, 0x6f, 0x82, 0xec, 0xce, 0xb8, 0xda, 0x96, 0xaf, 0xb4, 0xb5, 0xcf, 0xa4,
	0x43, 0x31, 0xed, 0x83, 0xf5, 0x95, 0xb6, 0x66, 0x7c, 0x15, 0xa7, 0xa8, 0x5d, 0xbe, 0x65, 0x74,
	0xa6, 0x61, 0xcc, 0xc4, 0xc2, 0xb4, 0xf9, 0xd1, 0x45, 0xe5, 0xb2, 0x43, 0x37, 0x76, 0xf0, 0xd7,
	0x0a, 0xb4, 0x9c, 0xc8, 0x7a, 0x8e, 0x8e, 0x6f, 0xcc, 0xf6, 0x1a, 0xb4, 0x3a, 0xbe, 0x21, 0x3f,
	0x84, 0x13, 0x5d, 0x26, 0x7f, 0x28, 0xb0, 0xc0, 0x6b, 0x26, 0x59, 0x14, 0xab, 0xb5, 0xd1, 0xb6,
	0x46, 0x0f, 0x1d, 0xe4, 0x19, 0x74, 0x36, 0xe0, 0x34, 0xfe, 0x13, 0x3a, 0xb1, 0xf7, 0x41, 0x9b,
	0x4b, 0x2c, 0x32, 0x4d, 0x55, 0x73, 0xbb, 0x73, 0x36, 0x19, 0xc0, 0x11, 0xc5, 0x08, 0xb9, 0x4a,
	0xd6, 0x53, 0xe4, 0xca, 0x1d, 0xc0, 0x1e, 0x36, 0xf8, 0x47, 0x0b, 0xba, 0xae, 0xd7, 0xca, 0x99,
	0xb4, 0x33, 0xb3, 0x5b, 0xfb, 0x33, 0xfb, 0x07, 0x70, 0x92, 0x30, 0x85, 0xb9, 0x0a, 0xcd, 0xa0,
	0x0c, 0x97, 0x2c, 0x5f, 0xba, 0xe2, 0x38, 0xb6, 0x8e, 0x2f, 0x35, 0xfe, 0x3b, 0x96, 0x2f, 0xc9,
	0xa7, 0xe0, 0xa0, 0x90, 0x49, 0x69, 0x23, 0xed, 0xc0, 0xec, 0x58, 0xf8, 0x4a, 0x4a, 0x13, 0x37,
	0x84, 0x8f, 0xf6, 0x39, 0x31, 0x5e, 0x2c, 0x95, 0xdb, 0xcb, 0xc9, 0x2e, 0xab, 0x71, 0x1c, 0xe4,
	0xa0, 0xaf, 0x44, 0x77, 0xb7, 0xec, 0xe6, 0xa0, 0xcf, 0x8a, 0x5c, 0x42, 0xef, 0x0e, 0x51, 0x86,
	0x09, 0xcb, 0x95, 0x19, 0x41, 0x9b, 0x6a, 0xeb, 0x6a, 0xfc, 0xf7, 0x2c, 0x57, 0x53, 0x83, 0x92,
	0x9f, 0x43, 0x5b, 0xa5, 0xe5, 0x94, 0x6a, 0x9a, 0x86, 0x3d, 0xd3, 0xed, 0xb5, 0x2f, 0xcd, 0xf0,
	0x55, 0xea, 0x00, 0x4f, 0xb9, 0xaf, 0xe0, 0x3f, 0x75, 0xf0, 0x4a, 0x78, 0x7f, 0x80, 0xd6, 0xde,
	0x39, 0x40, 0xaf, 0xa0, 0x9d, 0xaf, 0x79, 0x64, 0x43, 0xed, 0xdc, 0x79, 0xf6, 0x8e, 0x5f, 0x1c,
	0x4e, 0xd7, 0x3c, 0xb2, 0x14, 0xb9, 0xfb, 0x22, 0x13, 0xe8, 0xae, 0x58, 0x12, 0xcf, 0x99, 0x12,
	0x99, 0xe5, 0xd9, 0x99, 0xaf, 0x4f, 0xf1, 0xbc, 0x29, 0x57, 0x18, 0xb2, 0xce, 0x6a, 0xd7, 0x0c,
	0xfe, 0x5d, 0x01, 0xaf, 0xfc, 0xa1, 0xc7, 0x4f, 0xbb, 0xf1, 0xde, 0xa7, 0x5d, 0xf9, 0x80, 0xd3,
	0xae, 0x7e, 0xd0, 0x69, 0xd7, 0x1e, 0x3f, 0xed, 0x73, 0xf0, 0x23, 0xa6, 0xa2, 0x65, 0xcc, 0x17,
	0x61, 0x21, 0xdd, 0x6d, 0x0a, 0x25, 0xf4, 0x5a, 0x06, 0xff, 0xac, 0x40, 0x67, 0x6f, 0xfb, 0xba,
	0xd4, 0xcb, 0xfb, 0xda, 0x3d, 0x5c, 0x9c, 0x49, 0xc6, 0xd0, 0x92, 0xc5, 0x2c, 0xbc, 0xc3, 0xb5,
	0x3b, 0x9c, 0x2f, 0xde, 0x5b, 0xd4, 0xe1, 0xa4, 0x98, 0x3d, 0xc7, 0x35, 0x6d, 0x4a, 0xf3, 0x97,
	0x7c, 0x17, 0x8e, 0x56, 0x42, 0xe9, 0xac, 0xa4, 0x78, 0x8b, 0x99, 0xdb, 0xac, 0x6f, 0xb1, 0x89,
	0x86, 0x82, 0x11, 0x34, 0xed, 0x22, 0x3d, 0x41, 0xd5, 0x5a, 0xa2, 0xeb, 0x15, 0xf3, 0xad, 0x27,
	0xe8, 0x8a, 0x25, 0x05, 0x96, 0x73, 0xd8, 0x18, 0x03, 0x0a, 0x64, 0x92, 0x15, 0x1c, 0x8d, 0x00,
	0x39, 0xc5, 0x3f, 0x16, 0x98, 0x2b, 0x2d, 0xc2, 0x6d, 0x26, 0xd2, 0x52, 0x58, 0x3b, 0x5d, 0x40,
	0x43, 0x4e, 0xd1, 0x33, 0x68, 0x2b, 0xb1, 0xaf, 0xbb, 0xa7, 0x84, 0x75, 0x0e, 0x9e, 0xc3, 0xf1,
	0x0d, 0xb2, 0xc4, 0x3c, 0x0e, 0x1c, 0xe1, 0x8e, 0x44, 0x95, 0x7d, 0x89, 0xbe, 0x03, 0x20, 0xf5,
	0x60, 0xd0, 0xef, 0x11, 0x4b, 0xe5, 0xd1, 0x1d, 0x64, 0xf0, 0xdf, 0x3a, 0x9c, 0xdc, 0xb0, 0x7c,
	0x39, 0x13, 0x2c, 0x9b, 0x6f, 0xa6, 0xcb, 0xf7, 0xc0, 0x95, 0xc4, 0x7e, 0x8a, 0x47, 0x16, 0x74,
	0x49, 0xea, 0x76, 0x2c, 0x9f, 0xba, 0xae, 0xa8, 0x83, 0xa1, 0x7d, 0x0c, 0x0f, 0xcb, 0xc7, 0xf0,
	0xf0, 0x55, 0x19, 0x41, 0xb7, 0xc1, 0x7a, 0x1e, 0xce, 0xcb, 0xdb, 0xc9, 0xcd, 0xc3, 0xd2, 0xd6,
	0x07, 0x91, 0x62, 0x2a, 0xb2, 0x75, 0x58, 0xe4, 0x6c, 0x61, 0xa7, 0x46, 0x9d, 0xfa, 0x16, 0x7b,
	0xad, 0x21, 0x5d, 0x6f, 0xdb, 0x96, 0x2a, 0x0b, 0xc0, 0xd5, 0xfc, 0xc6, 0xe1, 0x8e, 0xea, 0x53,
	0x38, 0x4e, 0xd9, 0xbd, 0x79, 0x81, 0x95, 0x7b, 0xb1, 0xf7, 0x55, 0x27, 0x65, 0xf7, 0x5a, 0x42,
	0xb7, 0x99, 0x73, 0xf0, 0xcd, 0x3b, 0x2b, 0x8c, 0x44, 0xc1, 0x95, 0x99, 0xa9, 0x0d, 0x2d, 0x14,
	0x66, 0xf9, 0xb5, 0x46, 0xc8, 0x2f, 0xe0, 0x63, 0xb6, 0x5a, 0xb8, 0x0a, 0x97, 0x99, 0x88, 0x30,
	0xcf, 0x75, 0xb9, 0x98, 0x62, 0xb7, 0xb7, 0xd9, 0x29, 0x5b, 0x2d, 0xcc, 0x41, 0x4f, 0x36, 0x6e,
	0x53, 0xf3, 0xcf, 0xa0, 0xab, 0xa3, 0x42, 0x89, 0x99, 0x5d, 0xef, 0xae, 0xb8, 0x23, 0x8d, 0x4e,
	0x30, 0x33, 0x6b, 0xb4, 0xe6, 0x69, 0x9c, 0xe7, 0x38, 0xb7, 0x31, 0xb9, 0xb9, 0xeb, 0xda, 0xf4,
	0xc8, 0x82, 0xb6, 0x80, 0x0e, 0xca, 0xd4, 0x3f, 0x28, 0x53, 0x5d, 0x88, 0xb9, 0x62, 0x77, 0x68,
	0x6e, 0xbd, 0x36, 0xb5, 0x06, 0x99, 0x40, 0x6f, 0xab, 0x99, 0x1b, 0xa1, 0xfa, 0x21, 0xd1, 0x1d,
	0x7d, 0x5f, 0xf7, 0xcc, 0x41, 0x09, 0x6c, 0xbb, 0xc5, 0xb5, 0xd3, 0x56, 0x59, 0x0b, 0x0c, 0x7e,
	0x0d, 0xc7, 0x0f, 0x62, 0x48, 0x17, 0xc0, 0x41, 0x31, 0x5f, 0xf4, 0xbe, 0xa1, 0xed, 0xeb, 0x25,
	0x4b, 0x12, 0xe4, 0x0b, 0xcc, 0x7a, 0x15, 0xe2, 0x43, 0xeb, 0xe5, 0xed, 0x6d, 0x12, 0x73, 0xec,
	0x55, 0x47, 0x7f, 0xaf, 0x42, 0xf7, 0x85, 0xfd, 0x57, 0x6b, 0x8a, 0xd9, 0x2a, 0x8e, 0x90, 0xfc,
	0x04, 0x9a, 0x8e, 0xe9, 0xf4, 0xa0, 0x90, 0x7e, 0xa3, 0xff, 0xe5, 0x0a, 0xc8, 0x61, 0x83, 0x93,
	0x9f, 0x42, 0xcb, 0x3d, 0xb0, 0x9e, 0x5c, 0xf6, 0xd1, 0x23, 0xaf, 0x30, 0xf2, 0x2b, 0xf0, 0x77,
	0x7a, 0x93, 0x9c, 0xea, 0x98, 0xc3, 0x66, 0x0d, 0x9e, 0xe0, 0x24, 0x3f, 0x03, 0xaf, 0x6c, 0x43,
	0x62, 0xf8, 0x1f, 0x34, 0xe5, 0x93, 0x0b, 0x7f, 0x09, 0xed, 0x8d, 0xdc, 0x4f, 0x66, 0xfc, 0xad,
	0x47, 0x4f, 0xe5, 0x8b, 0xca, 0xac, 0x69, 0x02, 0x7f, 0xfc, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x62, 0x8f, 0x96, 0x5b, 0xa7, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ManagerServiceClient is the client API for ManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ManagerServiceClient interface {
	Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	NetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NetInfoResponse, error)
	PruneBlocks(ctx context.Context, in *PruneBlocksRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DealPeer(ctx context.Context, in *DealPeerRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	Dashboard(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ManagerService_DashboardClient, error)
}

type managerServiceClient struct {
	cc *grpc.ClientConn
}

func NewManagerServiceClient(cc *grpc.ClientConn) ManagerServiceClient {
	return &managerServiceClient{cc}
}

func (c *managerServiceClient) Status(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/pb.ManagerService/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) NetInfo(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*NetInfoResponse, error) {
	out := new(NetInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.ManagerService/NetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) PruneBlocks(ctx context.Context, in *PruneBlocksRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ManagerService/PruneBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) DealPeer(ctx context.Context, in *DealPeerRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pb.ManagerService/DealPeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managerServiceClient) Dashboard(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ManagerService_DashboardClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ManagerService_serviceDesc.Streams[0], "/pb.ManagerService/Dashboard", opts...)
	if err != nil {
		return nil, err
	}
	x := &managerServiceDashboardClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ManagerService_DashboardClient interface {
	Recv() (*DashboardResponse, error)
	grpc.ClientStream
}

type managerServiceDashboardClient struct {
	grpc.ClientStream
}

func (x *managerServiceDashboardClient) Recv() (*DashboardResponse, error) {
	m := new(DashboardResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ManagerServiceServer is the server API for ManagerService service.
type ManagerServiceServer interface {
	Status(context.Context, *empty.Empty) (*StatusResponse, error)
	NetInfo(context.Context, *empty.Empty) (*NetInfoResponse, error)
	PruneBlocks(context.Context, *PruneBlocksRequest) (*empty.Empty, error)
	DealPeer(context.Context, *DealPeerRequest) (*empty.Empty, error)
	Dashboard(*empty.Empty, ManagerService_DashboardServer) error
}

// UnimplementedManagerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedManagerServiceServer struct {
}

func (*UnimplementedManagerServiceServer) Status(ctx context.Context, req *empty.Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (*UnimplementedManagerServiceServer) NetInfo(ctx context.Context, req *empty.Empty) (*NetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NetInfo not implemented")
}
func (*UnimplementedManagerServiceServer) PruneBlocks(ctx context.Context, req *PruneBlocksRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PruneBlocks not implemented")
}
func (*UnimplementedManagerServiceServer) DealPeer(ctx context.Context, req *DealPeerRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DealPeer not implemented")
}
func (*UnimplementedManagerServiceServer) Dashboard(req *empty.Empty, srv ManagerService_DashboardServer) error {
	return status.Errorf(codes.Unimplemented, "method Dashboard not implemented")
}

func RegisterManagerServiceServer(s *grpc.Server, srv ManagerServiceServer) {
	s.RegisterService(&_ManagerService_serviceDesc, srv)
}

func _ManagerService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManagerService/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).Status(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_NetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).NetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManagerService/NetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).NetInfo(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_PruneBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PruneBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).PruneBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManagerService/PruneBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).PruneBlocks(ctx, req.(*PruneBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_DealPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DealPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagerServiceServer).DealPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.ManagerService/DealPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagerServiceServer).DealPeer(ctx, req.(*DealPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagerService_Dashboard_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagerServiceServer).Dashboard(m, &managerServiceDashboardServer{stream})
}

type ManagerService_DashboardServer interface {
	Send(*DashboardResponse) error
	grpc.ServerStream
}

type managerServiceDashboardServer struct {
	grpc.ServerStream
}

func (x *managerServiceDashboardServer) Send(m *DashboardResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _ManagerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.ManagerService",
	HandlerType: (*ManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _ManagerService_Status_Handler,
		},
		{
			MethodName: "NetInfo",
			Handler:    _ManagerService_NetInfo_Handler,
		},
		{
			MethodName: "PruneBlocks",
			Handler:    _ManagerService_PruneBlocks_Handler,
		},
		{
			MethodName: "DealPeer",
			Handler:    _ManagerService_DealPeer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dashboard",
			Handler:       _ManagerService_Dashboard_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "manager.proto",
}
