FROM tazhate/dockerfile-gox as builder

COPY . /gopath/src/github.com/MinterTeam/minter-go-node
WORKDIR /gopath/src/github.com/MinterTeam/minter-go-node
RUN apt-get update && apt-get install libleveldb-dev -y --no-install-recommends -q
RUN make build

FROM ubuntu:bionic

COPY --from=builder /gopath/src/github.com/MinterTeam/minter-go-node/build/minter/ /usr/bin/minter
RUN apt update && apt install libleveldb1v5 ca-certificates -y --no-install-recommends -q && \
    addgroup minteruser && \
    useradd --no-log-init -r -m -d /minter -g minteruser minteruser && \
    chown -R minteruser:minteruser /minter && \
    rm -rf /var/lib/apt/lists/*

USER minteruser
WORKDIR /minter
RUN mkdir /minter/data
EXPOSE 8843
ENTRYPOINT ["/usr/bin/minter"]
CMD ["node", "--home-dir", "/minter", "--state-sync"]
